version: '3.1'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    links:
      - db
  db:
    image: mysql:5.7
    ports:
      - "33060:3306"
    environment:
      MYSQL_ROOT_PASSWORD: foo
      MYSQL_DATABASE: shortener
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
